project:
  type: book
  output-dir: docs

book:
  title: "Business Statistics"
  author: "J. Alejandro Gelves"
  date: "09/6/2024"
  cover-image: cover.png
  chapters:
    - index.qmd
    - DescriptiveI.qmd
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual