<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Regression II – Business Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ProbabilityI.html" rel="next">
<link href="./RegressionI.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ed6da6eef3892af8a4b5ed59bfb951f5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-FWC3RCL4BF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FWC3RCL4BF');
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./RegressionII.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression II</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Business Statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Descriptive Stats I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive Stats II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveIII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Descriptive Statistics III</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveIV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Descriptive Stats IV</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DescriptiveV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Descriptive Stats V</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RegressionI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RegressionII.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ProbabilityI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ProbabilityII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ProbabilityIII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Probability III</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InferenceI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Inference I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InferenceII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inference II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InferenceIII.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./InfReg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Regression and Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">R Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-regression-line" id="toc-the-regression-line" class="nav-link active" data-scroll-target="#the-regression-line"><span class="header-section-number">7.1</span> The Regression Line</a></li>
  <li><a href="#measures-of-goodness-of-fit" id="toc-measures-of-goodness-of-fit" class="nav-link" data-scroll-target="#measures-of-goodness-of-fit"><span class="header-section-number">7.2</span> Measures of Goodness of Fit</a>
  <ul class="collapse">
  <li><a href="#coefficient-of-determination" id="toc-coefficient-of-determination" class="nav-link" data-scroll-target="#coefficient-of-determination">Coefficient of Determination</a></li>
  </ul></li>
  <li><a href="#multiple-regression" id="toc-multiple-regression" class="nav-link" data-scroll-target="#multiple-regression"><span class="header-section-number">7.3</span> Multiple Regression</a>
  <ul class="collapse">
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova">Anova</a></li>
  <li><a href="#adjusted-r2" id="toc-adjusted-r2" class="nav-link" data-scroll-target="#adjusted-r2">Adjusted <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#residual-standard-error" id="toc-residual-standard-error" class="nav-link" data-scroll-target="#residual-standard-error">Residual Standard Error</a></li>
  </ul></li>
  <li><a href="#regression-in-r" id="toc-regression-in-r" class="nav-link" data-scroll-target="#regression-in-r"><span class="header-section-number">7.4</span> Regression in R</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">7.5</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1">Exercise 1</a></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise 2</a></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3">Exercise 3</a></li>
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise 4</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression II</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<style>
details {
  background-color: #F8F9FA;
  padding: 5px;
  border: 1px solid #ddd; /* Light border */
  border-radius: 5px; /* Rounded corners */
  margin: 10px 0; /* Spacing */
}

details summary {
  cursor: pointer; /* Pointer cursor for interactivity */
}
</style>
<p>Quantifying relationships between variables is an important skill in business analytics. The regression line, representing the best linear fit between two variables, enables businesses to make predictions, identify trends, and optimize strategies using data-driven insights. Understanding how to calculate and interpret a regression line provides the foundation for analyzing business relationships, such as the effect of advertising on sales or customer satisfaction on revenue. Below, we delve into generating and analyzing a regression line.</p>
<section id="the-regression-line" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="the-regression-line"><span class="header-section-number">7.1</span> The Regression Line</h2>
<p>The regression line is calculated to minimize the average distance (or errors) between the line and the observed data points. It is defined by two key components: a <strong>slope</strong> (<span class="math inline">\(\beta\)</span>) and an <strong>intercept</strong> (<span class="math inline">\(\alpha\)</span>). Mathematically, the regression line is expressed as: <span class="math display">\[\hat{y_i}=\hat{\alpha}+\hat{\beta}x_i\]</span></p>
<p>where <span class="math inline">\(\hat{y_i}\)</span> are the predicted values of <span class="math inline">\(y\)</span> given the <span class="math inline">\(x\)</span>’s. The <strong>slope</strong> determines the steepness of the line. The estimate quantifies how much a unit increase in <span class="math inline">\(x\)</span> changes <span class="math inline">\(y\)</span>. We can easily calculate the slope by using the covariance between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>, and the variance of <span class="math inline">\(x\)</span>. Mathematically we have:</p>
<p><span class="math display">\[\hat{\beta}= \frac {s_{xy}}{s_{x}^2}\]</span></p>
<p>The <strong>intercept</strong> determines where the line crosses the <span class="math inline">\(y\)</span> axis. In other words it returns the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x\)</span> is zero. Once we have the slope of the regression line we can estimate the intercept by: <span class="math display">\[\hat{\alpha}=\bar{y}-\hat{\beta}\bar{x}\]</span></p>
<p><strong>Example:</strong> Let’s examine a data set on Price and Advertisement. In general, one expects that when a company advertises, it can convince consumers to pay more for their product. Below is the data used to calculate the regression line, followed by its interpretation.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Advertisement (x)</th>
<th style="text-align: center;">Price (y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">10</td>
</tr>
</tbody>
</table>
<p>The data shows a clear relationship between advertisement and price: when advertisement spending is high, price also tends to be high. This suggests a direct relationship between the two variables. In a previous chapter, we learned to quantify such relationships using covariance and the correlation coefficient.</p>
<p>In this section, we aim to answer two key questions:</p>
<ol type="1">
<li>Effectiveness: How much can we increase the price for every additional dollar spent on advertisement?</li>
<li>Prediction: What is the predicted price if we have a budget of 6 for advertisement?</li>
</ol>
<p>The regression line allows us to answer these questions by quantifying the relationship between the two variables. Specifically, if we can estimate the regression line, as shown below, we can answer these questions.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/reg.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Let’s start by calculating the slope of the regression line, as this will help us answer the effectiveness question. The slope measures how much the price increases for every additional dollar spent on advertisement. It is calculated using the formula: <span class="math inline">\(\hat{\beta}= \frac {s_{xy}}{s_{x}^2}\)</span>. Given that the covariance is <span class="math inline">\(3.67\)</span> and the variance of <span class="math inline">\(x\)</span> is <span class="math inline">\(1.67\)</span>, the slope of the regression line is <span class="math inline">\(\hat{\beta}= \frac{3.67}{1.67}=2.2\)</span>. This tells us that for every additional dollar spent on advertisement, price increases by <span class="math inline">\(2.2\)</span> on average. Thus, we have answered the effectiveness question.</p>
<p>Next, we calculate the intercept to complete the regression line and answer the prediction question. The intercept represents the predicted price when advertisement spending is zero. It is calculated as: <span class="math inline">\(\hat{\alpha}=\bar{y}-\hat{\beta}\bar{x}\)</span>. Since the mean of advertisement is <span class="math inline">\(2.5\)</span> and the mean of price is <span class="math inline">\(7\)</span>, the intercept is <span class="math inline">\(\hat{\alpha}=7-2.2(2.5)=1.5\)</span>. This means that if we do not advertise, the predicted price is zero.</p>
<p>The regression line can be completed by using the intercept and slope that we have estimated above. In particular, the regression line is <span class="math inline">\(\hat{y_i}=1.5+2.2x_i\)</span>. With this equation we can now establish that if we had a budget of <span class="math inline">\(6\)</span> for advertisement, our predicted price would be <span class="math inline">\(\hat{y_i}=1.5+2.2(6)=14.7\)</span>. This answers our prediction question.</p>
<p>In conclusion regression line has allowed us to answer both questions: 1. The effectiveness of advertisement: For every dollar spent, the price increases by <span class="math inline">\(2.2\)</span>. 2. The predicted price: With an advertisement budget of <span class="math inline">\(6\)</span>, the predicted price is <span class="math inline">\(14.7\)</span>.</p>
<p>This demonstrates the value of regression analysis in quantifying relationships and making informed predictions.</p>
</section>
<section id="measures-of-goodness-of-fit" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="measures-of-goodness-of-fit"><span class="header-section-number">7.2</span> Measures of Goodness of Fit</h2>
<p>When analyzing the effectiveness of a regression model, it is crucial to assess how well the model fits the data. This is where measures of goodness of fit come into play. Below we revisit the coefficient of determination or <span class="math inline">\(R^2\)</span>.</p>
<section id="coefficient-of-determination" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="coefficient-of-determination">Coefficient of Determination</h3>
<p>The <strong>coefficient of determination</strong> or <span class="math inline">\(R^2\)</span> is the percent of the variation in <span class="math inline">\(y\)</span> that is explained by changes in <span class="math inline">\(x\)</span>. The higher the <span class="math inline">\(R^2\)</span> the better the explanatory power of the model. The <span class="math inline">\(R^2\)</span> is always between [0,1]. To calculate use <span class="math inline">\(R^2=SSR/SST\)</span>. Below you can find how to calculate each component of the <span class="math inline">\(R^2\)</span>.</p>
<ul>
<li><p><span class="math inline">\(SSR\)</span> (Sum of Squares due to Regression) is the part of the variation in <span class="math inline">\(y\)</span> explained by the model. Mathematically, <span class="math inline">\(SSR=\sum{(\hat{y_i}-\bar{y})^2}\)</span>.</p></li>
<li><p><span class="math inline">\(SSE\)</span> (Sum of Squares due to Error) is the part of the variation in <span class="math inline">\(y\)</span> that is unexplained by the model. Mathematically, <span class="math inline">\(SSE=\sum{(y_i-\hat{y_i})^2}\)</span>.</p></li>
<li><p><span class="math inline">\(SST\)</span> (Sum of Squares Total) is the total variation of <span class="math inline">\(y\)</span> with respect to the mean. Mathematically, <span class="math inline">\(SST=\sum{(y_i-\bar{y})^2}\)</span>.</p></li>
<li><p>Note that <span class="math inline">\(SST=SSR+SSE\)</span>.</p></li>
</ul>
<p><strong>Example:</strong> Let’s consider data on the Weight (<span class="math inline">\(y\)</span>) and Exercise (<span class="math inline">\(x\)</span>) of a particular person.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Weight (y)</th>
<th style="text-align: center;">Exercise (x)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">165</td>
<td style="text-align: center;">45</td>
</tr>
<tr class="even">
<td style="text-align: center;">170</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">168</td>
<td style="text-align: center;">25</td>
</tr>
<tr class="even">
<td style="text-align: center;">164</td>
<td style="text-align: center;">30</td>
</tr>
<tr class="odd">
<td style="text-align: center;">165</td>
<td style="text-align: center;">40</td>
</tr>
</tbody>
</table>
<p>Now, if we were to predict the weight of this person, we could consider just using the mean value (i.e., <span class="math inline">\(166.4\)</span>). If this were our guess, then the mistakes (errors) we would have made with this prediction are quantified by the <span class="math inline">\(SST=25.2\)</span>. Below, you can see these mistakes visually.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/rs2.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>For example, in day <span class="math inline">\(1\)</span> the mean prediction is <span class="math inline">\(166.4\)</span>, but the actual measure is <span class="math inline">\(165\)</span>. We have made a mistake of <span class="math inline">\(-1.4\)</span> by using the mean as our predicted weight. To get a sense of the overall mistake we have made, we add up all of the squared errors made by using the mean as a prediction. Hence, <span class="math inline">\(SST= (-1.4)^2 + (3.6)^2 + (1.6)^2 + (-2.4)^2 + (-1.4)^2= 25.2\)</span>.</p>
<p>The idea behind regression is that another variable related to weight can help us make a better prediction. Generally speaking, you burn calories if you exercise, so your weight should be lower when exercising. Hence, adding information on how many minutes a person exercises in a day should allow us to predict someone’s weight better. The <span class="math inline">\(SSE\)</span> quantifies the mistakes made by a prediction generated from regression. To understand this, let’s start by looking at the regression line for Weight and Exercise.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/rs3.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The image highlights how the regression line can reduce the errors in our prediction. Consider the point with <span class="math inline">\(y\)</span> coordinate <span class="math inline">\(168\)</span>. The error using the mean is <span class="math inline">\(1.6\)</span> (the green and yellow lines). However, if we update our prediction using the regression line, the mistake is reduced to <span class="math inline">\(168-167.17=0.83\)</span> (the green line). Squaring all these deviations from the line and adding them gives us <span class="math inline">\(SSE=0.81+0.29+0.69+5.76+0.02=7.57\)</span>. Note how using the regression line has helped us reduce the errors in our prediction.</p>
<p>If regression has helped us make smaller mistakes, it has also helped us explain more of the variation in Weight (<span class="math inline">\(y\)</span>). In the graph, the gap between the mean and the <span class="math inline">\(168\)</span> point has been reduced by the amount highlighted in yellow (<span class="math inline">\(0.77\)</span>). If we square and add up all of the “improvements,” we get <span class="math inline">\(SSR=5.29+9.4+0.59+0+2.35=17.63\)</span>. In sum, the regression line has closed the gap of the prediction errors made by using the mean by <span class="math inline">\(R^2=\frac{SSR}{SST} \approx 0.7\)</span> or 70%.</p>
</section>
</section>
<section id="multiple-regression" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="multiple-regression"><span class="header-section-number">7.3</span> Multiple Regression</h2>
<p>If we were to predict weight we could use several other variables that are related to get a better prediction. <em>Multiple regression</em> is a technique used predict a variable using more than one independent variable. Mathematically, you would be estimating <span class="math inline">\(\hat{y_i}=\hat{\beta_0}+\hat{\beta_1}x_1+\hat{\beta_2}x_2...+\hat{\beta_k}x_k\)</span>, where <span class="math inline">\(k\)</span> is the total number of independent variables included in the regression model.</p>
<p><strong>Example:</strong> Let’s consider an additional variable in our Weight and Exercise example. The table below includes information on Calories (z).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Weight (y)</th>
<th style="text-align: center;">Exercise (x)</th>
<th style="text-align: center;">Calories (z)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">165</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">1200</td>
</tr>
<tr class="even">
<td style="text-align: center;">170</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">1260</td>
</tr>
<tr class="odd">
<td style="text-align: center;">168</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">1220</td>
</tr>
<tr class="even">
<td style="text-align: center;">164</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">1180</td>
</tr>
<tr class="odd">
<td style="text-align: center;">165</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">1190</td>
</tr>
</tbody>
</table>
<p>The regression line can be estimated using computer software and is given by <span class="math inline">\(\hat{y_i}=83.96-0.025x+0.069z\)</span>. A few things can be concluded from the regression line. First, as the amount of exercise increases our weight tends to go down, but as we consume more calories the weight tends to go up. Second, the effectiveness of calories seems to be better that that of exercise. For every minute exercise our weight goes down on average by 0.025 pounds. However, if we reduce our calorie consumption by 1, then our weight goes down by 0.069 pounds.</p>
<section id="anova" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="anova">Anova</h3>
<p>We can further explore the importance of each variable using the Anova table. This table helps us understand how well our regression model explains the dependent variable. For now, we will use this table to show the <span class="math inline">\(SSR\)</span> generated by each variable as well as to track the errors. Using computer software we get the following table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Source</th>
<th style="text-align: center;">Sum Squares</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">x</td>
<td style="text-align: center;">17.63</td>
</tr>
<tr class="even">
<td style="text-align: center;">z</td>
<td style="text-align: center;">6.55</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Residuals</td>
<td style="text-align: center;">1.01</td>
</tr>
</tbody>
</table>
<p>The table shows that x “closes the gap” with respect to the mean prediction by <span class="math inline">\(17.63\)</span>. If we add calories to our model, we further decrease the gap by another <span class="math inline">\(6.55\)</span>. In sum, using them together reduces the <span class="math inline">\(SST\)</span> by <span class="math inline">\(24.18\)</span>, which in turn reduced the <span class="math inline">\(SSE\)</span> to only <span class="math inline">\(1.01\)</span>. Finally, the <span class="math inline">\(R^2\)</span> also increases from <span class="math inline">\(0.7\)</span> to now <span class="math inline">\(0.96\)</span>, <span class="math inline">\(R^2= \frac{17.63+6.55}{25.5}\)</span>.</p>
</section>
<section id="adjusted-r2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="adjusted-r2">Adjusted <span class="math inline">\(R^2\)</span></h3>
<p>The <strong>adjusted</strong> <span class="math inline">\(R^2\)</span> recognizes that the <span class="math inline">\(R^2\)</span> is a non-decreasing function of the number of independent variables included in the model. This metric penalizes a model with more explanatory variables relative to a simpler model. It is calculated by <span class="math inline">\(1-(1-R^2) \frac {n-1}{n-k-1}\)</span>, where <span class="math inline">\(k\)</span> is the number of explanatory variables used in the model and <span class="math inline">\(n\)</span> is the sample size. For our weight example <span class="math inline">\(adjusted R^2=1-(1-0.96) \frac{5-1}{5-2-1}=0.9196\)</span>.</p>
</section>
<section id="residual-standard-error" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="residual-standard-error">Residual Standard Error</h3>
<p>The <strong>Residual Standard Error</strong> estimates the average dispersion of the data points around the regression line. Recall, that we have calculated the squared deviation from the regression line by using <span class="math inline">\(SSE\)</span>. Hence if we want to find an average deviation we can divide using the number of observations and then find a square root to go back to linear values. In particular you can use <span class="math inline">\(s_e =\sqrt{\frac{SSE}{n-k-1}}\)</span>, where <span class="math inline">\(k\)</span> is the number of independent variables used in your regression. For our example with only exercise in our model <span class="math inline">\(s_e=\sqrt{\frac{7.57}{5-1-1}}=1.59\)</span>. If we include both calories and exercise then <span class="math inline">\(s_e=\sqrt{\frac{1.01}{5-2-1}}=0.71\)</span>.</p>
</section>
</section>
<section id="regression-in-r" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="regression-in-r"><span class="header-section-number">7.4</span> Regression in R</h2>
<p>Below we conduct regression analysis in R, using the weight data. Let’s start by creating a tibble to store the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>d<span class="ot">&lt;-</span><span class="fu">tibble</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="dv">165</span>,<span class="dv">170</span>,<span class="dv">168</span>,<span class="dv">164</span>,<span class="dv">165</span>),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">x=</span><span class="fu">c</span>(<span class="dv">45</span>,<span class="dv">10</span>,<span class="dv">25</span>,<span class="dv">30</span>,<span class="dv">40</span>),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">z=</span><span class="fu">c</span>(<span class="dv">1200</span>,<span class="dv">1260</span>,<span class="dv">1220</span>,<span class="dv">1180</span>,<span class="dv">1190</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can first visualize the relationship between x and y using <code>ggplot</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>d <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>y,<span class="at">x=</span>x),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">pch=</span><span class="dv">21</span>, <span class="at">col=</span><span class="st">"black"</span>, <span class="at">bg=</span><span class="st">"blue"</span>, <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_clean</span>() <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y=</span>y,<span class="at">x=</span>x),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">method=</span><span class="st">"lm"</span>,<span class="at">se=</span>F,<span class="at">formula=</span>y<span class="sc">~</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="RegressionII_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The regression line is estimated using the <code>lm()</code> command as shown below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x, <span class="at">data=</span>d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can retrieve the coefficients by either using the <code>coef()</code> function or the <code>summary()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = d)

Residuals:
      1       2       3       4       5 
 0.9000  0.5333  0.8333 -2.4000  0.1333 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 171.00000    1.87913  91.000 2.93e-06 ***
x            -0.15333    0.05799  -2.644   0.0774 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.588 on 3 degrees of freedom
Multiple R-squared:  0.6997,    Adjusted R-squared:  0.5996 
F-statistic: 6.991 on 1 and 3 DF,  p-value: 0.07738</code></pre>
</div>
</div>
<p>The summary function confirms our results for the <span class="math inline">\(R^2\)</span> and coefficients. If we wanted to make a prediction we can use the <code>predict()</code> function with the fit object as input. Below we predict y when x is equal to 4.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit,<span class="at">newdata =</span> <span class="fu">tibble</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
170.3867 </code></pre>
</div>
</div>
<p>Note that the values of <span class="math inline">\(x\)</span> must be entered as a tibble in the function. We can run multiple regression by just adding z to our fit object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>z, <span class="at">data=</span>d)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x + z, data = d)

Residuals:
      1       2       3       4       5 
-0.3375 -0.3375  0.7875 -0.3375  0.2250 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 83.96250   24.20433   3.469   0.0740 .
x           -0.02500    0.04413  -0.567   0.6281  
z            0.06875    0.01911   3.598   0.0693 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7115 on 2 degrees of freedom
Multiple R-squared:  0.9598,    Adjusted R-squared:  0.9196 
F-statistic: 23.89 on 2 and 2 DF,  p-value: 0.04018</code></pre>
</div>
</div>
<p>Lastly, to obtain the Anova table we can use the <code>anova()</code> command.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: y
          Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
x          1 17.6333 17.6333  34.831 0.02753 *
z          1  6.5542  6.5542  12.947 0.06931 .
Residuals  2  1.0125  0.5062                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Below we summarize the R functions: - The <code>lm()</code> function to estimates the linear regression model.</p>
<ul>
<li><p>The <code>predict()</code> function uses the linear model object to predict values. New data is entered as a data frame or tibble.</p></li>
<li><p>The <code>coef()</code> function returns the model’s coefficients.</p></li>
<li><p>The <code>summary()</code> function returns the model’s coefficients, and goodness of fit measures.</p></li>
<li><p>The <code>Anova()</code> function creates the anova table for a regression. you must provide an object that contains the result of the <code>lm()</code> function.</p></li>
</ul>
</section>
<section id="exercises" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="exercises"><span class="header-section-number">7.5</span> Exercises</h2>
<p>The following exercises will help you get practice on Regression Line estimation and interpretation. In particular, the exercises work on:</p>
<ul>
<li><p>Estimating the slope and intercept.</p></li>
<li><p>Calculating measures of goodness of fit.</p></li>
<li><p>Prediction using the regression line.</p></li>
</ul>
<p>Answers are provided below. Try not to peak until you have a formulated your own answer and double checked your work for any mistakes.</p>
<section id="exercise-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-1">Exercise 1</h3>
<p>For the following exercises, make your calculations by hand and verify results using R functions when possible.</p>
<ol type="1">
<li>Consider the data below. Calculate the deviations from the mean for each variable and use the results to estimate the regression line. Use R to verify your result. On average by how much does <em>y</em> increase per unit increase of <em>x</em>?</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>x</strong></th>
<th style="text-align: center;">20</th>
<th style="text-align: center;">21</th>
<th style="text-align: center;">15</th>
<th style="text-align: center;">18</th>
<th style="text-align: center;">25</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>y</strong></td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">22</td>
</tr>
</tbody>
</table>
<details>
<summary>
Answer
</summary>
<p><em>The regression lines is</em> <span class="math inline">\(\hat{y}=-4.93+1.09x\)</span>. For each unit increase in x, y increases on average <span class="math inline">\(1.09\)</span>.</p>
<p><em>Start by generating the deviations from the mean for each variable. For x the deviations are:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">20</span>,<span class="dv">21</span>,<span class="dv">15</span>,<span class="dv">18</span>,<span class="dv">25</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>(devx<span class="ot">&lt;-</span>x<span class="sc">-</span><span class="fu">mean</span>(x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.2  1.2 -4.8 -1.8  5.2</code></pre>
</div>
</div>
<p><em>Next, find the deviations for y:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>y<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">17</span>,<span class="dv">19</span>,<span class="dv">12</span>,<span class="dv">13</span>,<span class="dv">22</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>(devy<span class="ot">&lt;-</span>y<span class="sc">-</span><span class="fu">mean</span>(y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.4  2.4 -4.6 -3.6  5.4</code></pre>
</div>
</div>
<p><em>For the slope we need to find the deviation squared of the x’s. This can easily be done in R:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>(devx2<span class="ot">&lt;-</span>devx<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.04  1.44 23.04  3.24 27.04</code></pre>
</div>
</div>
<p><em>The slope is calculated by</em> <span class="math inline">\(\frac{\sum_{i=i}^{n} (x_{i}-\bar{x})(y_{i}-\bar{y})}{\sum_{i=i}^{n} (x_{i}-\bar{x})^2}\)</span>. In R we can just find the ratio between the summations of (devx)(devy) and devx2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>(slope<span class="ot">&lt;-</span><span class="fu">sum</span>(devx<span class="sc">*</span>devy)<span class="sc">/</span><span class="fu">sum</span>(devx2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.087591</code></pre>
</div>
</div>
<p><em>The intercept is given by</em> <span class="math inline">\(\bar{y}-\beta(\bar{x})\)</span>. In R we find that the intercept is equal to:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>(intercept<span class="ot">&lt;-</span><span class="fu">mean</span>(y)<span class="sc">-</span>slope<span class="sc">*</span><span class="fu">mean</span>(x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -4.934307</code></pre>
</div>
</div>
<p><em>Our results can be easily verified by using the <code>lm()</code> and <code>coef()</code> functions in R.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>fitEx1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fitEx1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           x 
  -4.934307    1.087591 </code></pre>
</div>
</div>
</details>
<ol start="2" type="1">
<li>Calculate <em>SST</em>, <em>SSR</em>, and <em>SSE</em>. Confirm your results in R. What is the <span class="math inline">\(R^2\)</span>? What is the Standard Error estimate? Is the regression line a good fit for the data?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>SST is</em> <span class="math inline">\(69.2\)</span>, SSR is <span class="math inline">\(64.82\)</span> and SSE is <span class="math inline">\(4.38\)</span> (note that <span class="math inline">\(SSR+SSE=SST\)</span>). The <span class="math inline">\(R^2\)</span> is just <span class="math inline">\(\frac{SSR}{SST}=0.94\)</span> and the Standard Error estimate is <span class="math inline">\(1.21\)</span>. They both indicate a great fit of the regression line to the data.</p>
<p><em>Let’s start by calculating the SST. This is just</em> <span class="math inline">\(\sum{(y_{i}-\bar{y})^2}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>(SST<span class="ot">&lt;-</span><span class="fu">sum</span>((y<span class="sc">-</span><span class="fu">mean</span>(y))<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 69.2</code></pre>
</div>
</div>
<p><em>Next, we can calculate SSR. This is calculated by the following formula</em> <span class="math inline">\(\sum{(\hat{y_{i}}-\bar{y})^2}\)</span>. To obtain the predicted values in R, we can use the output of the <code>lm()</code> function. Recall our fitEx1 object created in Exercise 1. It has fitted.values included:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>(SSR<span class="ot">&lt;-</span><span class="fu">sum</span>((fitEx1<span class="sc">$</span>fitted.values<span class="sc">-</span><span class="fu">mean</span>(y))<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 64.82044</code></pre>
</div>
</div>
<p><em>The ratio of SSR to SST is the</em> <span class="math inline">\(R^2\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>(R2<span class="ot">&lt;-</span>SSR<span class="sc">/</span>SST)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9367115</code></pre>
</div>
</div>
<p><em>Finally, let’s calculate SSE</em> <span class="math inline">\(\sum{(y_{i}-\hat{y_{i}})^2}\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>(SSE<span class="ot">&lt;-</span><span class="fu">sum</span>((y<span class="sc">-</span>fitEx1<span class="sc">$</span>fitted.values)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.379562</code></pre>
</div>
</div>
<p><em>With the SSE we can calculate the Standard Error estimate:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(SSE<span class="sc">/</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.208244</code></pre>
</div>
</div>
<p><em>We can confirm these results using the <code>summary()</code> function.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fitEx1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x)

Residuals:
      1       2       3       4       5 
 0.1825  1.0949  0.6204 -1.6423 -0.2555 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  -4.9343     3.2766  -1.506  0.22916   
x             1.0876     0.1632   6.663  0.00689 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.208 on 3 degrees of freedom
Multiple R-squared:  0.9367,    Adjusted R-squared:  0.9156 
F-statistic:  44.4 on 1 and 3 DF,  p-value: 0.00689</code></pre>
</div>
</div>
</details>
<ol start="3" type="1">
<li>Assume that <em>x</em> is observed to be <em>32</em>, what is your prediction of <em>y</em>? How confident are you in this prediction?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>If</em> <span class="math inline">\(x=32\)</span> then <span class="math inline">\(\hat{y}=29.87\)</span>. The regression is a good fit, so we can feel good about our prediction. However, we would be concerned about the sample size of the data.</p>
<p><em>In R we can obtain a prediction by using the <code>predict()</code> function. This function requires a data frame as an input for new data.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fitEx1, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">32</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
29.86861 </code></pre>
</div>
</div>
</details>
</section>
<section id="exercise-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-2">Exercise 2</h3>
<p>You will need the <strong>Education</strong> data set to answer this question. You can find the data set at https://jagelves.github.io/Data/Education.csv . The data shows the years of education (<em>Education</em>), and annual salary in thousands (<em>Salary</em>) for a sample of <span class="math inline">\(100\)</span> people.</p>
<ol type="1">
<li>Estimate the regression line using R. By how much does an extra year of education increase the annual salary on average? What is the salary of someone without any education?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>An extra year of education increases the annual salary about</em> <span class="math inline">\(5,300\)</span> dollars (slope). A person that has no education would be expected to earn <span class="math inline">\(17,2582\)</span> dollars (intercept).</p>
<p><em>Start by loading the data in R:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>Education<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"https://jagelves.github.io/Data/Education.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Next, let’s use the <code>lm()</code> function to estimate the regression line and obtain the coefficients:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fitEducation<span class="ot">&lt;-</span><span class="fu">lm</span>(Salary<span class="sc">~</span>Education, <span class="at">data =</span> Education)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(fitEducation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   Education 
  17.258190    5.301149 </code></pre>
</div>
</div>
</details>
<ol start="2" type="1">
<li>Confirm that the regression line is a good fit for the data. What is the estimated salary of a person with <span class="math inline">\(16\)</span> years of education?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>The</em> <span class="math inline">\(R^2\)</span> is <span class="math inline">\(0.668\)</span> and the standard error is <span class="math inline">\(21\)</span>. The line is a moderately good fit. If someone has <span class="math inline">\(16\)</span> years of experience, the regression line would predict a salary of <span class="math inline">\(102,000\)</span> dollars.</p>
<p><em>Let’s get the</em> <span class="math inline">\(R^2\)</span> and the Standard Error estimate by using the <code>summary()</code> function and fitEx1 object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fitEducation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Salary ~ Education, data = Education)

Residuals:
    Min      1Q  Median      3Q     Max 
-62.177  -9.548   1.988  15.330  45.444 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  17.2582     4.0768   4.233  5.2e-05 ***
Education     5.3011     0.3751  14.134  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 20.98 on 98 degrees of freedom
Multiple R-squared:  0.6709,    Adjusted R-squared:  0.6675 
F-statistic: 199.8 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><em>Lastly, let’s use the regression line to predict the salary for someone who has</em> <span class="math inline">\(16\)</span> years of education.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fitEducation, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Education=</span><span class="fu">c</span>(<span class="dv">16</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
102.0766 </code></pre>
</div>
</div>
</details>
</section>
<section id="exercise-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-3">Exercise 3</h3>
<p>You will need the <strong>FoodSpend</strong> data set to answer this question. You can find this data set at https://jagelves.github.io/Data/FoodSpend.csv .</p>
<ol type="1">
<li>Omit any NA’s that the data has. Create a dummy variable that is equal to <span class="math inline">\(1\)</span> if an individual owns a home and <span class="math inline">\(0\)</span> if the individual doesn’t. Find the mean of your dummy variable. What proportion of the sample owns a home?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>Approximately,</em> <span class="math inline">\(36\)</span>% of the sample owns a home.</p>
<p><em>Start by loading the data into R and removing all NA’s:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>Spend<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"https://jagelves.github.io/Data/FoodSpend.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 80 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): OwnHome
dbl (1): Food

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>Spend<span class="ot">&lt;-</span><span class="fu">na.omit</span>(Spend)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>To create a dummy variable for OwnHome we can use the <code>ifelse()</code> function:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>Spend<span class="sc">$</span>dummyOH<span class="ot">&lt;-</span><span class="fu">ifelse</span>(Spend<span class="sc">$</span>OwnHome<span class="sc">==</span><span class="st">"Yes"</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>The average of the dummy variable is given by:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Spend<span class="sc">$</span>dummyOH)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3625</code></pre>
</div>
</div>
</details>
<ol start="2" type="1">
<li>Run a regression with <em>Food</em> being the dependent variable and your dummy variable as the independent variable. What is the interpretation of the intercept and slope?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>The intercept is the average food expenditure of individuals without homes (</em><span class="math inline">\(6417\)</span>). The slope, is the difference in food expenditures between individuals that do have homes minus those who don’t. We then conclude that individuals that do have a home spend about <span class="math inline">\(-2516\)</span> less on food than those who don’t have homes.</p>
<p><em>To run the regression use the <code>lm()</code> function:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(Food<span class="sc">~</span>dummyOH,<span class="at">data=</span>Spend)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Food ~ dummyOH, data = Spend)

Coefficients:
(Intercept)      dummyOH  
       6473        -3418  </code></pre>
</div>
</div>
</details>
<ol start="3" type="1">
<li>Now run a regression with <em>Food</em> being the independent variable and your dummy variable as the dependent variable. What is the interpretation of the intercept and slope? Hint: you might want to plot the scatter diagram and the regression line.</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>The scatter plot shows that most of the points for home owners are below</em> <span class="math inline">\(6000\)</span>. For non-home owners they are mainly above <span class="math inline">\(6000\)</span>. The line can be used to predict the likelihood of owning a home given someones food expenditure. The intercept is above one, but still it gives us the indication that it is likely that low food expenditures are highly predictive of owning a home. The slope tells us how that likelihood changes as the food expenditures increase by 1. In general, the likelihood of owning a home decreases as the food expenditure increases.</p>
<p><em>Run the <code>lm()</code> function once again:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>fitFood<span class="ot">&lt;-</span><span class="fu">lm</span>(dummyOH<span class="sc">~</span>Food,<span class="at">data=</span>Spend)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(fitFood)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)          Food 
 1.4320766616 -0.0002043632 </code></pre>
</div>
</div>
<p><em>For the scatter plot use the following code:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>Spend <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>dummyOH,<span class="at">x=</span>Food), </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">col=</span><span class="st">"black"</span>, <span class="at">pch=</span><span class="dv">21</span>, <span class="at">bg=</span><span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y=</span>dummyOH,<span class="at">x=</span>Food), <span class="at">method=</span><span class="st">"lm"</span>,</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula=</span>y<span class="sc">~</span>x, <span class="at">se=</span>F) <span class="sc">+</span> </span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_clean</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="RegressionII_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</details>
</section>
<section id="exercise-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exercise-4">Exercise 4</h3>
<p>You will need the <strong>Population</strong> data set to answer this question. You can find this data set at https://jagelves.github.io/Data/Population.csv .</p>
<ol type="1">
<li>Run a regression of <em>Population</em> on <em>Year</em>. How well does the regression line fit the data?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>If we follow the</em> <span class="math inline">\(R^2=0.81\)</span> the model fits the data very well.</p>
<p><em>Let’s load the data from the web:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>Population<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"https://jagelves.github.io/Data/Population.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 16492 Columns: 4
── Column specification
──────────────────────────────────────────────────────── Delimiter: "," chr
(1): Country.Name dbl (3): ...1, Year, Population
ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
Specify the column types or set `show_col_types = FALSE` to quiet this message.
• `` -&gt; `...1`</code></pre>
</div>
</div>
<p><em>Now let’s filter the data so that we can focus on the population for Japan.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>Japan<span class="ot">&lt;-</span><span class="fu">filter</span>(Population,Country.Name<span class="sc">==</span><span class="st">"Japan"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Next, we can run the regression of Population against the Year. Let’s also run the <code>summary()</code> function to obtain the fit and the coefficients.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">&lt;-</span><span class="fu">lm</span>(Population<span class="sc">~</span>Year,<span class="at">data=</span>Japan)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Population ~ Year, data = Japan)

Residuals:
     Min       1Q   Median       3Q      Max 
-9583497 -4625571  1214644  4376784  5706004 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -988297581   68811582  -14.36   &lt;2e-16 ***
Year            555944      34569   16.08   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4871000 on 60 degrees of freedom
Multiple R-squared:  0.8117,    Adjusted R-squared:  0.8086 
F-statistic: 258.6 on 1 and 60 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</details>
<ol start="2" type="1">
<li>Create a prediction for Japan’s population in 2030. What is your prediction?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>The prediction for</em> <span class="math inline">\(2030\)</span> is about <span class="math inline">\(140\)</span> million people.</p>
<p><em>Let’s use the <code>predict()</code> function:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit,<span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Year=</span><span class="fu">c</span>(<span class="dv">2030</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
140268585 </code></pre>
</div>
</div>
</details>
<ol start="3" type="1">
<li>Create a scatter diagram and include the regression line. How confident are you of your prediction after looking at the diagram?</li>
</ol>
<details>
<summary>
Answer
</summary>
<p><em>After looking at the scatter plot, it seems unlikely that the population in Japan will hit</em> <span class="math inline">\(140\)</span> million. Population has been decreasing in Japan!</p>
<p><em>Use the <code>plot()</code> and <code>abline()</code> functions to create the figure.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>Japan <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>Population,<span class="at">x=</span>Year), </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">col=</span><span class="st">"black"</span>, <span class="at">pch=</span><span class="dv">21</span>, <span class="at">bg=</span><span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y=</span>Population,<span class="at">x=</span>Year), </span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula=</span>y<span class="sc">~</span>x, <span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span>F) <span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_clean</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="RegressionII_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</details>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./RegressionI.html" class="pagination-link" aria-label="Regression I">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression I</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ProbabilityI.html" class="pagination-link" aria-label="Probability I">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability I</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Business Statistics by J. Alejandro Gelves.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>